#pragma once
#include "Dll.h"
#include "Heap.h"
#include "Fiber.h"

void EmuCloseHandle(uc_engine* uc, DWORD tab);
void EmuConnectNamedPipe(uc_engine* uc, DWORD tab);
void EmuCopyFile(uc_engine* uc, DWORD tab, TCHAR existingFileName[], TCHAR newFileName[], BOOL bFailIfExists);
void EmuCopyFileA(uc_engine* uc, DWORD tab);
void EmuCopyFileW(uc_engine* uc, DWORD tab);
void EmuCreateDirectory(uc_engine* uc, DWORD tab, TCHAR lpPathName[], DWORD lpSecurityAttributes);
void EmuCreateDirectoryEx(uc_engine* uc, DWORD tab, TCHAR templateDirectory[], TCHAR newDirectory[], DWORD lpSecurityAttributes);
void EmuCreateDirectoryA(uc_engine* uc, DWORD tab);
void EmuCreateDirectoryExA(uc_engine* uc, DWORD tab);
void EmuCreateDirectoryExW(uc_engine* uc, DWORD tab);
void EmuCreateDirectoryW(uc_engine* uc, DWORD tab);
void EmuCreateFile(uc_engine* uc, DWORD tab, TCHAR fileName[], TCHAR genericAccess[], TCHAR shareMode[], DWORD lpSecurityAttributes, TCHAR createType[], TCHAR attribute[], DWORD hTemplateFile, DWORD dwDesiredAccess, DWORD dwShareMode, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes);
void EmuCreateFileMapping(uc_engine* uc, DWORD tab, DWORD hFile, DWORD lpFileMappingAttributes, TCHAR pageAccess[], DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, TCHAR name[], DWORD flProtect);
void EmuCreateFileA(uc_engine* uc, DWORD tab);
void EmuCreateFileMappingA(uc_engine* uc, DWORD tab);
void EmuCreateFileMappingW(uc_engine* uc, DWORD tab);
void EmuCreateFileW(uc_engine* uc, DWORD tab);
void EmuCreateMutex(uc_engine* uc, DWORD tab, DWORD lpMutexAttributes, BOOL bInitialOwner, TCHAR name[]);
void EmuCreateMutexEx(uc_engine* uc, DWORD tab, DWORD lpMutexAttributes, TCHAR name[], DWORD dwFlags, TCHAR mutexAccess[], DWORD dwDesiredAccess);
void EmuCreateMutexA(uc_engine* uc, DWORD tab);
void EmuCreateMutexExA(uc_engine* uc, DWORD tab);
void EmuCreateMutexExW(uc_engine* uc, DWORD tab);
void EmuCreateMutexW(uc_engine* uc, DWORD tab);
void EmuCreateNamedPipe(uc_engine* uc, DWORD tab, TCHAR name[], DWORD dwOpenMode, DWORD dwPipeMode, DWORD nMaxInstances, DWORD nOutBufferSize, DWORD nInBufferSize, DWORD nDefaultTimeOut, DWORD lpSecurityAttributes);
void EmuCreateNamedPipeA(uc_engine* uc, DWORD tab);
void EmuCreateNamedPipeW(uc_engine* uc, DWORD tab);
void EmuCreatePipe(uc_engine* uc, DWORD tab);
void EmuCreateProcess(uc_engine* uc, DWORD tab, TCHAR applicationName[], TCHAR commandLine[], DWORD lpProcessAttributes, DWORD lpThreadAttributes, DWORD bInheritHandles, TCHAR creationFlags[], DWORD lpEnvironment, TCHAR currentDirectory[], DWORD lpStartupInfo, DWORD lpProcessInformation);
void EmuCreateProcessAsUser(uc_engine* uc, DWORD tab, DWORD hToken, TCHAR applicationName[], TCHAR commandLine[], DWORD lpProcessAttributes, DWORD lpThreadAttributes, DWORD bInheritHandles, TCHAR creationFlags[], DWORD lpEnvironment, TCHAR currentDirectory[], DWORD lpStartupInfo, DWORD lpProcessInformation);
void EmuCreateProcessA(uc_engine* uc, DWORD tab);
void EmuCreateProcessAsUserA(uc_engine* uc, DWORD tab);
void EmuCreateProcessAsUserW(uc_engine* uc, DWORD tab);
void EmuCreateProcessW(uc_engine* uc, DWORD tab);
void EmuCreateRemoteThread(uc_engine* uc, DWORD tab);
void EmuCreateRemoteThreadEx(uc_engine* uc, DWORD tab);
void EmuCreateThread(uc_engine* uc, DWORD tab);
void EmuCreateToolhelp32Snapshot(uc_engine* uc, DWORD tab);
void EmuDecodePointer(uc_engine* uc, DWORD tab);
void EmuDeleteCriticalSection(uc_engine* uc, DWORD tab);
void EmuDeleteFile(uc_engine* uc, DWORD tab, TCHAR fileName[]);
void EmuDeleteFileA(uc_engine* uc, DWORD tab);
void EmuDeleteFileW(uc_engine* uc, DWORD tab);
void EmuDisconnectNamedPipe(uc_engine* uc, DWORD tab);
void EmuDuplicateHandle(uc_engine* uc, DWORD tab);
void EmuEncodePointer(uc_engine* uc, DWORD tab);
void EmuEnterCriticalSection(uc_engine* uc, DWORD tab);
void EmuExitProcess(uc_engine* uc, DWORD tab);
void EmuExitThread(uc_engine* uc, DWORD tab);
void EmuFindClose(uc_engine* uc, DWORD tab);
void EmuFindFirstFile(uc_engine* uc, DWORD tab);
void EmuFindFirstFileA(uc_engine* uc, DWORD tab);
void EmuFindFirstFileExA(uc_engine* uc, DWORD tab);
void EmuFindFirstFileExW(uc_engine* uc, DWORD tab);
void EmuFindFirstFileW(uc_engine* uc, DWORD tab);
void EmuFindNextFile(uc_engine* uc, DWORD tab);
void EmuFindNextFileA(uc_engine* uc, DWORD tab);
void EmuFindNextFileW(uc_engine* uc, DWORD tab);
void EmuFlsAlloc(uc_engine* uc, DWORD tab);
void EmuFlsFree(uc_engine* uc, DWORD tab);
void EmuFlsGetValue(uc_engine* uc, DWORD tab);
void EmuFlsSetValue(uc_engine* uc, DWORD tab);
void EmuFreeLibrary(uc_engine* uc, DWORD tab);
void EmuGetCurrentProcess(uc_engine* uc, DWORD tab);
void EmuGetCurrentProcessId(uc_engine* uc, DWORD tab);
void EmuGetCurrentThread(uc_engine* uc, DWORD tab);
void EmuGetCurrentThreadId(uc_engine* uc, DWORD tab);
void EmuGetLastError(uc_engine* uc, DWORD tab);
void EmuGetModuleFileName(uc_engine* uc, DWORD tab, DWORD hModule, DWORD lpFilename, DWORD nSize, BOOL isW);
void EmuGetModuleFileNameA(uc_engine* uc, DWORD tab);
void EmuGetModuleFileNameW(uc_engine* uc, DWORD tab);
void EmuGetModuleHandle(uc_engine* uc, DWORD tab, TCHAR moduleName[]);
void EmuGetModuleHandleEx(uc_engine* uc, DWORD tab, DWORD dwFlags, TCHAR moduleName[], DWORD phModule);
void EmuGetModuleHandleA(uc_engine* uc, DWORD tab);
void EmuGetModuleHandleExA(uc_engine* uc, DWORD tab);
void EmuGetModuleHandleExW(uc_engine* uc, DWORD tab);
void EmuGetModuleHandleW(uc_engine* uc, DWORD tab);
void EmuGetProcAddress(uc_engine* uc, DWORD tab);
void EmuGetProcessHeap(uc_engine* uc, DWORD tab);
void EmuGetSystemTimeAsFileTime(uc_engine* uc, DWORD tab);
void EmuHeapAlloc(uc_engine* uc, DWORD tab);
void EmuHeapCreate(uc_engine* uc, DWORD tab);
void EmuHeapFree(uc_engine* uc, DWORD tab);
void EmuHeapSize(uc_engine* uc, DWORD tab);
void EmuInitializeCriticalSection(uc_engine* uc, DWORD tab);
void EmuInitializeCriticalSectionEx(uc_engine* uc, DWORD tab);
void EmuIsBadReadPtr(uc_engine* uc, DWORD tab);
void EmuIsProcessorFeaturePresent(uc_engine* uc, DWORD tab);
void EmuIsWow64Process(uc_engine* uc, DWORD tab);
void EmuLeaveCriticalSection(uc_engine* uc, DWORD tab);
void EmuLoadLibrary(uc_engine* uc, DWORD tab, TCHAR libFileName[]);
void EmuLoadLibraryEx(uc_engine* uc, DWORD tab, TCHAR libFileName[], DWORD hFile, DWORD dwFlags);
void EmuLoadLibraryA(uc_engine* uc, DWORD tab);
void EmuLoadLibraryExA(uc_engine* uc, DWORD tab);
void EmuLoadLibraryExW(uc_engine* uc, DWORD tab);
void EmuLoadLibraryW(uc_engine* uc, DWORD tab);
void EmuOpenMutex(uc_engine* uc, DWORD tab, DWORD dwDesiredAccess, BOOL bInheritHandle, TCHAR mutexAccess[], TCHAR name[]);
void EmuOpenMutexA(uc_engine* uc, DWORD tab);
void EmuOpenMutexW(uc_engine* uc, DWORD tab);
void EmuQueryPerformanceCounter(uc_engine* uc, DWORD tab);
void EmuSetErrorMode(uc_engine* uc, DWORD tab);
void EmuSetLastError(uc_engine* uc, DWORD tab);
void EmuSleep(uc_engine* uc, DWORD tab);
void EmuSleepEx(uc_engine* uc, DWORD tab);
void EmuTlsAlloc(uc_engine* uc, DWORD tab);
void EmuTlsFree(uc_engine* uc, DWORD tab);
void EmuTlsGetValue(uc_engine* uc, DWORD tab);
void EmuTlsSetValue(uc_engine* uc, DWORD tab);
void EmuVirtualAlloc(uc_engine* uc, DWORD tab);
void EmuVirtualAllocEx(uc_engine* uc, DWORD tab);
void EmuVirtualFree(uc_engine* uc, DWORD tab);
void EmuVirtualFreeEx(uc_engine* uc, DWORD tab);
void EmuVirtualProtect(uc_engine* uc, DWORD tab);
void EmuVirtualProtectEx(uc_engine* uc, DWORD tab);
void EmuWaitForSingleObject(uc_engine* uc, DWORD tab);
void EmuWaitForSingleObjectEx(uc_engine* uc, DWORD tab);
void EmuWinExec(uc_engine* uc, DWORD tab);